apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp
  name: myapp
  namespace: tekton-demo
spec:
  # Use a different type if LoadBalancer is not supported on your k8s environment
  type: LoadBalancer
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: myapp
